POST http://localhost:8080/events
Content-Type: application/json
Authorization: 

{
  "name": "Test event",
  "description": "A test event",
  "location": "A test location",
  "dateTime": "2025-01-01T15:31:00.000Z"
}
