PUT http://localhost:8080/events/1
Content-Type: application/json

{
  "name": "Test event (updated)",
  "description": "A test event (updated)",
  "location": "A test location (updated)",
  "dateTime": "2025-01-01T16:00:00.000Z"
}
